### ISSUE TITLE
Where is alchemical-gromacs.py?

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/pymbar-datasets#4]

**Comment by kyleabeauchamp** [comment]
Is this the most recent version?

**Comment by kyleabeauchamp** [comment]
https://github.com/choderalab/pymbar-examples/blob/master/alchemical-free-energy/alchemical-gromacs.py

**Comment by jchodera** [comment]
Looping in @mrshirts

**Comment by mrshirts** [comment]
Gone, now use alchemlyb: https://github.com/alchemistry/alchemlyb
